--
-- PostgreSQL database dump
--

-- Dumped from database version 13.21
-- Dumped by pg_dump version 13.21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: exercise_set_listening; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (10, 'medium', 'In the heart of the city, streetdance has become a vibrant expression of culture and creativity. Dancers gather in parks and on sidewalks, showcasing their skills and styles. Some prefer breakdancing, with its dynamic spins and floor moves, while others lean towards hip-hop, emphasizing rhythm and storytelling through their movements. The community is supportive, often encouraging new dancers to join in and learn. Competitions are held regularly, where crews battle each other, and the energy is electric. Streetdance is more than just movement; it’s a way for individuals to connect and tell their stories through dance.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_4b80d713-d103-4ce6-a56b-14677693e3e3.mp3', '{"topic": "streetdance", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 1, "options": ["Inside dance studios", "In parks and on sidewalks", "On television shows", "In theaters"], "question": "What is a common location for streetdance performances?", "explanation": "The passage specifically mentions that dancers gather in parks and on sidewalks, which are common locations for streetdance performances."}, {"answer": 2, "options": ["Hip-hop", "Contemporary", "Breakdancing", "Jazz"], "question": "Which style of streetdance is noted for its dynamic spins and floor moves?", "explanation": "The transcript states that breakdancing is characterized by dynamic spins and floor moves, making it the correct answer."}, {"answer": 2, "options": ["Competition among dancers", "Isolation of individual styles", "Support for new dancers", "Strict adherence to traditional forms"], "question": "What aspect of streetdance is emphasized in the community mentioned?", "explanation": "The text highlights the supportive nature of the community, encouraging new dancers to join and learn, which emphasizes support for new dancers."}]', '2025-09-05 11:28:05.470768');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (11, 'medium', 'In recent years, hip hop has not only dominated the music charts but also influenced fashion, language, and culture worldwide. Artists like Kendrick Lamar and Cardi B have used their platforms to address social issues, from poverty to systemic racism. The genre has evolved from its origins in the Bronx during the 1970s, where it began as a form of expression for marginalized communities. Today, hip hop is a global phenomenon, with artists collaborating across borders and genres, demonstrating its versatility and broad appeal. As hip hop continues to grow, it remains a powerful tool for storytelling and activism, engaging listeners in conversations about real-life challenges.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_bb3d7915-1e46-43da-946e-c246fb27ef19.mp3', '{"topic": "hiphop", "difficulty": "medium", "numQuestions": 4}', '[{"answer": 1, "options": ["Only fashion", "Language and culture", "Only social issues", "None of the above"], "question": "What has hip hop influenced besides music?", "explanation": "Hip hop has influenced not just music but also fashion, language, and culture, making it a multifaceted genre."}, {"answer": 0, "options": ["Kendrick Lamar and Cardi B", "Jay-Z and Nas", "Drake and Lil Wayne", "Eminem and 50 Cent"], "question": "Who are two contemporary hip hop artists mentioned in the transcript?", "explanation": "The transcript specifically mentions Kendrick Lamar and Cardi B as influential contemporary hip hop artists."}, {"answer": 2, "options": ["Los Angeles", "Atlanta", "The Bronx", "Chicago"], "question": "Where did hip hop originate?", "explanation": "Hip hop originated in the Bronx during the 1970s, which is noted in the transcript."}, {"answer": 1, "options": ["It is merely entertainment.", "It serves as a tool for storytelling and activism.", "It is only a fashion statement.", "It has no significant impact."], "question": "What role does hip hop play in society according to the transcript?", "explanation": "The transcript states that hip hop remains a powerful tool for storytelling and activism, engaging listeners on important issues."}]', '2025-09-05 11:33:09.979535');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (12, 'easy', 'A: Hi, Sarah! Have you finished the report for the meeting tomorrow?  
B: Not yet, John. I need to gather some more data.  
A: Do you need any help?  
B: Yes, could you help me find the sales figures for last quarter?  
A: Sure! I can look them up for you.  
B: Thanks! I really appreciate it.  
A: No problem. We need to be prepared for the presentation.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_0f5e2271-8a5a-4136-9c14-afe63520905e.mp3', '{"genre": "dialogue", "topic": "business", "difficulty": "easy", "numQuestions": 3}', '[{"answer": 1, "options": ["Planning a vacation", "Preparing for a meeting", "Going to a restaurant", "Organizing a party"], "question": "What is the main topic of the conversation?", "explanation": "The conversation is focused on completing a report for a meeting, indicating that the main topic is about preparing for a business meeting."}, {"answer": 0, "options": ["Finding sales figures", "Writing a report", "Making a presentation", "Scheduling a meeting"], "question": "What does Sarah need help with?", "explanation": "Sarah specifically asks John for help in finding the sales figures for last quarter, which shows that this is the area she needs assistance with."}, {"answer": 2, "options": ["He is busy and cannot help", "He is indifferent", "He is happy to help", "He is annoyed"], "question": "How does John feel about helping Sarah?", "explanation": "John responds positively, saying ''Sure! I can look them up for you,'' indicating that he is willing and happy to help Sarah."}]', '2025-09-05 11:58:57.63917');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (13, 'medium', 'In today''s meeting, Sarah and Tom discussed the quarterly sales report. Sarah pointed out that while overall sales have increased, the online sales segment has seen significant growth. Tom agreed and suggested that they allocate more resources to enhance their online marketing strategies. He also mentioned the importance of customer feedback in improving their product offerings. Sarah concluded by stating that they should prepare a proposal for the next meeting to address these points.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_64710ec2-1e63-4fe1-8904-317f6e5e9381.mp3', '{"genre": "short", "topic": "business", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 1, "options": ["A. In-store sales", "B. Online sales", "C. Wholesale sales", "D. International sales"], "question": "What segment of sales saw significant growth according to Sarah?", "explanation": "Sarah specifically mentioned that the online sales segment has seen significant growth."}, {"answer": 1, "options": ["A. Reduce marketing budget", "B. Allocate more resources to online marketing", "C. Focus solely on in-store sales", "D. Increase product prices"], "question": "What did Tom suggest they do to improve online sales?", "explanation": "Tom suggested allocating more resources to enhance their online marketing strategies to improve online sales."}, {"answer": 1, "options": ["A. A financial audit", "B. A proposal addressing their discussion points", "C. A review of employee performance", "D. A discussion on company culture"], "question": "What did Sarah propose for the next meeting?", "explanation": "Sarah concluded by stating that they should prepare a proposal for the next meeting to address the points discussed."}]', '2025-09-05 12:00:27.996605');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (14, 'medium', 'A: Hey, did you check out that new hip-hop album that dropped last week?
B: Yeah, I did! The beats are insane, and the lyrics are so fresh.
A: I know, right? I love how the artist mixes old school vibes with modern sounds.
B: Exactly! And the way they tell stories through their music is just amazing. It''s like a journey.
A: Totally! Who''s your favorite artist right now?
B: I''m really into that new rapper, they have such a unique style. What about you?', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_5f26ab18-2ed1-4eaa-8dcd-ebc521852b04.mp3', '{"genre": "dialogue", "topic": "hiphop", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 1, "options": ["A. The beats are terrible.", "B. The beats are insane and the lyrics are fresh.", "C. They haven''t listened to it yet.", "D. They prefer pop music."], "question": "What does Speaker B think about the new hip-hop album?", "explanation": "Speaker B describes the beats as ''insane'' and the lyrics as ''fresh,'' indicating they have a positive opinion about the album."}, {"answer": 1, "options": ["A. The artist''s popularity.", "B. The mix of old school vibes with modern sounds.", "C. The length of the songs.", "D. The artist''s fashion style."], "question": "What does Speaker A appreciate about the artist''s music?", "explanation": "Speaker A admires how the artist blends ''old school vibes with modern sounds,'' showcasing their appreciation for the musical style."}, {"answer": 1, "options": ["A. The dance moves associated with the genre.", "B. The storytelling through music.", "C. The album covers.", "D. The popularity of hip-hop artists."], "question": "What aspect of hip-hop does Speaker B highlight?", "explanation": "Speaker B mentions the ''way they tell stories through their music,'' emphasizing the storytelling aspect of hip-hop."}]', '2025-09-05 12:02:01.718278');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (15, 'medium', 'Emily: I can''t believe we finally got engaged! It feels so surreal.
Jack: I know, right? I’ve been dreaming about this day for so long.
Emily: What do you think we should do next? Should we tell our families?
Jack: Absolutely! They’ll be so excited. We should also start thinking about the wedding plans.
Emily: Yes! I already have some ideas about the venue. Maybe a beach wedding?
Jack: That sounds perfect! Let’s make a list of everything we need to do.
Emily: Great idea! I can’t wait to start this journey together.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_835ff47a-b0a8-4d09-a4f4-12d97690723e.mp3', '{"genre": "short", "topic": "fiance", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 2, "options": ["Planning a vacation", "Discussing a new job", "Talking about their engagement", "Choosing a restaurant"], "question": "What is the main topic of the conversation?", "explanation": "The conversation centers around Emily and Jack discussing their recent engagement and the plans that follow."}, {"answer": 2, "options": ["A church wedding", "A garden wedding", "A beach wedding", "A city hall wedding"], "question": "What type of wedding does Emily suggest?", "explanation": "Emily mentions that she has ideas about a beach wedding, indicating her preference for that setting."}, {"answer": 1, "options": ["He is indifferent.", "He is excited and has been dreaming about it.", "He wants to delay the wedding.", "He is worried about the costs."], "question": "What is Jack''s reaction to the engagement?", "explanation": "Jack expresses his excitement and indicates that he has been dreaming about the engagement, showing a positive reaction."}]', '2025-09-09 10:43:11.168859');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (16, 'hard', 'In the realm of love, the concept of fiancée carries a weight of anticipation and promise. It signifies not just a relationship, but a commitment to a future intertwined with another soul. As Sarah gazed at the sparkling ring on her finger, she reflected on the journey that had led her to this moment. The laughter they shared, the challenges they overcame, and the dreams they built together painted a vivid picture of their love story, one that was just beginning to unfold.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_23e38486-3812-4deb-b6e4-8987a87b3ed5.mp3', '{"genre": "short", "topic": "fiance", "difficulty": "hard", "numQuestions": 3}', '[{"answer": 1, "options": ["A casual relationship", "A commitment to a future together", "A fleeting romance", "An end to dating"], "question": "What does the term ''fiancée'' signify according to the passage?", "explanation": "The passage describes ''fiancée'' as a commitment to a future intertwined with another soul, indicating a serious relationship."}, {"answer": 2, "options": ["Her past relationships", "The challenges of her job", "The journey that led to her engagement", "The opinions of her friends"], "question": "What does Sarah reflect on while looking at her ring?", "explanation": "Sarah reflects on the journey that led her to the moment of her engagement, emphasizing her thoughts on their shared experiences."}, {"answer": 1, "options": ["Melancholic", "Joyful and hopeful", "Indifferent", "Conflicted"], "question": "How is the tone of the narrative best described?", "explanation": "The narrative conveys a joyful and hopeful tone as it discusses the promise and excitement of engagement."}]', '2025-09-09 10:50:32.592767');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (17, 'hard', 'A: Have you thought about what kind of engagement ring you''d like?
B: I have! I really want something unique, maybe a vintage design.
A: That sounds beautiful. Do you have a specific style in mind?
B: Yes, something with intricate details and perhaps a colored gemstone.
A: Oh, like a sapphire or an emerald?
B: Exactly! I think they add a nice touch compared to traditional diamonds.
A: Have you looked at any jewelers yet?
B: Not yet, but I plan to do some research this weekend.
A: Great! It''s important to find the right one, especially for such a big decision.
B: I agree. I want it to be perfect for the occasion.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_82b54a30-ebc7-4f0d-9d2a-0336e2c8797c.mp3', '{"genre": "dialogue", "topic": "fiance", "difficulty": "hard", "numQuestions": 3}', '[{"answer": 0, "options": ["Unique and vintage", "Simple and modern", "Traditional diamond", "Gold band only"], "question": "What type of ring does B prefer?", "explanation": "B specifically mentions wanting something unique and vintage."}, {"answer": 2, "options": ["Ruby", "Diamond", "Sapphire or emerald", "Amethyst"], "question": "What kind of gemstone does B consider instead of a diamond?", "explanation": "B mentions liking sapphires and emeralds as alternatives to traditional diamonds."}, {"answer": 2, "options": ["They should be the cheapest", "They should be well-reviewed", "Finding the right one for such a big decision", "They should have a large inventory"], "question": "What does A suggest is important when choosing a jeweler?", "explanation": "A emphasizes the importance of finding the right jeweler for a significant decision."}]', '2025-09-09 10:51:24.543655');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (18, 'medium', 'In the heart of the bustling city, a unique festival was about to begin. The annual Popping Festival attracted people from all walks of life, eager to see the dazzling displays of popping balloons. Children squealed with delight as colorful balloons exploded in a shower of glitter, while adults marveled at the creativity of balloon artists. The sound of pops echoed through the streets, creating an electrifying atmosphere that filled everyone with joy. As the sun set, the sky transformed into a canvas of vibrant colors, igniting the excitement of the night ahead.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_062c731a-827c-4f37-8c60-8f32bfe79a4d.mp3', '{"genre": "short", "topic": "Popping", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 1, "options": ["A music festival", "The annual Popping Festival", "A food festival", "A sports competition"], "question": "What event is taking place in the city?", "explanation": "The passage specifically mentions that the unique festival is the annual Popping Festival."}, {"answer": 1, "options": ["Food stalls", "Balloon displays", "Live music", "Street performers"], "question": "What do children enjoy at the festival?", "explanation": "The passage states that children squealed with delight as colorful balloons exploded, indicating their enjoyment of the balloon displays."}, {"answer": 1, "options": ["It becomes quieter", "It fills with excitement", "It starts to rain", "The lights turn off"], "question": "How does the atmosphere change as the sun sets?", "explanation": "The passage describes the sunset transforming the sky into vibrant colors, igniting excitement for the night ahead, indicating an increase in atmosphere."}]', '2025-09-09 11:31:39.697872');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (19, 'medium', 'In the heart of the city, a vibrant street dance scene thrives. Every weekend, dancers of all ages gather at the local plaza, showcasing their unique styles and moves. The infectious beats of hip-hop music fill the air, drawing in crowds who cheer and clap along. Among them is Maya, a talented dancer known for her incredible footwork and energy. As she takes the stage, her friends cheer her on, and the excitement is palpable. The street becomes a canvas for expression, where each dancer tells their own story through movement, creating a sense of community and joy.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_1714cf01-24cf-49f2-a965-b6444039e371.mp3', '{"genre": "short", "topic": "streetdance", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 0, "options": ["A local plaza", "A dance studio", "A school gym", "A theater"], "question": "What is the primary setting of the street dance scene described?", "explanation": "The passage specifically mentions that the dancers gather at the local plaza."}, {"answer": 2, "options": ["Jazz", "Classical", "Hip-hop", "Rock"], "question": "What type of music is playing during the street dance?", "explanation": "The transcript states that hip-hop music fills the air during the dance."}, {"answer": 0, "options": ["Her incredible footwork", "Her costumes", "Her age", "Her friends"], "question": "What makes Maya stand out as a dancer?", "explanation": "Maya is described as a talented dancer known for her incredible footwork and energy."}]', '2025-09-09 11:56:53.736701');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (20, 'medium', 'In the heart of spring, the garden bursts into a vibrant display of colors. Tulips stand tall, their petals unfurling like painted cups, while daffodils sway gently in the breeze, their golden heads nodding in agreement with the warmth of the sun. Nearby, a cluster of daisies adds a touch of whimsy, their white petals framing bright yellow centers like little suns. As bees buzz busily from flower to flower, the air fills with the sweet scent of blooming jasmine, inviting everyone to pause and appreciate the beauty of nature''s artistry.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_ee9703c2-f258-4957-9548-3f7f428a4275.mp3', '{"genre": "short", "topic": "flower", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 0, "options": ["Spring", "Summer", "Autumn", "Winter"], "question": "What season is the garden described in the passage?", "explanation": "The passage mentions that it is the heart of spring, indicating the season."}, {"answer": 1, "options": ["Daisies", "Tulips", "Daffodils", "Jasmine"], "question": "Which flower is described as having petals that unfurl like painted cups?", "explanation": "Tulips are described as standing tall with petals unfurling like painted cups."}, {"answer": 2, "options": ["Mint", "Roses", "Jasmine", "Lavender"], "question": "What scent fills the air in the garden?", "explanation": "The passage explicitly mentions that the air is filled with the sweet scent of blooming jasmine."}]', '2025-09-09 12:55:29.181258');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (21, 'medium', 'In a small town, a massive storm was brewing. The clouds darkened the sky, and the wind howled through the streets, warning everyone to take cover. As the first raindrops began to fall, the townspeople hurried to secure their homes. Suddenly, a loud crash echoed through the air as a tree fell, blocking the main road. Emergency services were quick to respond, but the town''s spirit remained unbroken. Neighbors helped each other clear the debris, showcasing the strength of their community even in the face of adversity.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_d99f8182-416d-4879-8693-e1f6fa349c64.mp3', '{"genre": "short", "topic": "breaking", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 0, "options": ["A storm", "An earthquake", "A flood", "A wildfire"], "question": "What natural event was occurring in the town?", "explanation": "The passage describes a massive storm brewing in the town."}, {"answer": 1, "options": ["They ignored the warnings", "They secured their homes", "They went to the beach", "They celebrated a festival"], "question": "What did the townspeople do as the storm approached?", "explanation": "The townspeople hurried to secure their homes as the storm approached."}, {"answer": 2, "options": ["They panicked and ran away", "They called for help and waited", "They worked together to clear the debris", "They took pictures and posted online"], "question": "How did the community respond to the fallen tree blocking the road?", "explanation": "The passage mentions that neighbors helped each other clear the debris, showing their community spirit."}]', '2025-09-09 13:30:53.924666');
INSERT INTO public.exercise_set_listening (id, difficulty, transcript, audio_url, spec, items, created_at) VALUES (22, 'medium', 'Breaking dance, often known as breakdancing, emerged from the vibrant streets of the South Bronx in the late 1970s. This dynamic dance style combines acrobatics, rhythm, and creativity, allowing dancers to express themselves through powerful moves and intricate footwork. With its roots in hip-hop culture, breaking has evolved over the decades, gaining international recognition and becoming a staple in dance competitions worldwide. Today, it’s not just a dance form; it’s a way of life for many, encompassing a sense of community and artistic expression.', 'https://pub-2d8e555bef8640a498a78558f89973ad.r2.dev/audio/listening_ee46c987-f1d2-47f5-8093-c06029679d7f.mp3', '{"genre": "short", "topic": "breakingdance", "difficulty": "medium", "numQuestions": 3}', '[{"answer": 0, "options": ["The South Bronx", "California", "Paris", "Tokyo"], "question": "Where did breaking dance originate?", "explanation": "Breaking dance originated in the South Bronx, which is mentioned as its birthplace in the passage."}, {"answer": 0, "options": ["Acrobatics, rhythm, and creativity", "Singing, acting, and painting", "Martial arts, ballet, and jazz", "None of the above"], "question": "What elements does breaking dance combine?", "explanation": "The passage states that breaking dance combines acrobatics, rhythm, and creativity."}, {"answer": 0, "options": ["A global phenomenon recognized in competitions", "A form of classical dance", "A silent art form", "A type of fitness exercise"], "question": "What has breaking evolved into over the decades?", "explanation": "The passage explains that breaking has gained international recognition and become a staple in dance competitions."}]', '2025-09-09 13:55:59.369525');


--
-- Name: exercise_set_listening_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercise_set_listening_id_seq', 22, true);


--
-- PostgreSQL database dump complete
--

