springdoc:
  packages-to-scan: com.example.aitutor.web

server:
  port: ${PORT:8080}             # Railway 給 PORT，本機 fallback 8080
  forward-headers-strategy: native

logging.level:
  com.example.aitutor: DEBUG
  org.hibernate.SQL: warn

openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://roundhouse.proxy.rlwy.net:5432/railway}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:aryytxuUQPgZRCXAxGxiMRnlWAMOJEoU}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false

  flyway:
    enabled: true
