springdoc:
  packages-to-scan: com.example.aitutor.web

server:
  port: ${PORT:8080}             # Railway 給 PORT，本機 fallback 8080
  forward-headers-strategy: native

logging.level:
  com.example.aitutor: DEBUG
  org.hibernate.SQL: warn

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini

spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: qCPpZpBZZVjxGSvthPqbofjkSKnHTOMP

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false

  flyway:
    enabled: false
