# src/main/resources/application.yml
springdoc:
  packages-to-scan: com.example.aitutor.web

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}   # 本機預設 local，Railway 設 prod

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false

  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native

logging.level:
  com.example.aitutor: DEBUG
  org.hibernate.SQL: warn

openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini

# ---------- local（開發機） ----------
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/aitutor
    username: postgres
    password: talen168168

# ---------- prod（Railway） ----------
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
