name: Build & Push Images to Docker Hub

on:
  push:
    branches: [ "main" ]
    # 可選：只在 backend/ 或 frontend/ 有變動才建置
    # paths:
    #   - "backend/**"
    #   - "frontend/**"
  # 可選：發 tag 就推版本 tag
  tag:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare tags
        id: prep
        run: |
          REPO="${{ secrets.DOCKERHUB_USERNAME }}"
          SHA_TAG=${GITHUB_SHA::7}
          #  image 名稱
          echo "BACKEND_IMAGE=${REPO}/aitutor-backend" >> $GITHUB_OUTPUT
          echo "FRONTEND_IMAGE=${REPO}/aitutor-frontend" >> $GITHUB_OUTPUT
          # 預設標籤：sha 與 latest（也可加入分支名）
          echo "BACKEND_TAGS=${REPO}/aitutor-backend:latest,${REPO}/aitutor-backend:${SHA_TAG}" >> $GITHUB_OUTPUT
          echo "FRONTEND_TAGS=${REPO}/aitutor-frontend:latest,${REPO}/aitutor-frontend:${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.prep.outputs.BACKEND_TAGS }}
          cache-from: type=registry,ref=${{ steps.prep.outputs.BACKEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ steps.prep.outputs.BACKEND_IMAGE }}:buildcache,mode=max

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.prep.outputs.FRONTEND_TAGS }}
          cache-from: type=registry,ref=${{ steps.prep.outputs.FRONTEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ steps.prep.outputs.FRONTEND_IMAGE }}:buildcache,mode=max